server:
  port: 9000

logger:
  level: debug
  format: pretty

sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/

endpoints:
  - path: /graphql
    from: countries

  - path: /persisted
    from: countries
    plugins:
      - type: persisted_operations
        store:
          source: file
          path: ./temp/persisted_operations_store.json
          format: json_key_value
        protocols:
          - type: apollo_manifest_extensions
          - type: document_id
          - type: http_get
            document_id_from:
              source: search_query
              name: docId
            variables_from:
              source: header
              name: "X-GraphQL-Variables"
        allow_non_persisted: true

  - path: /test
    from: countries
    plugins:
      - type: cors
      - type: graphiql
      - type: http_get
        allow: true
        # mutations: false
    #   - type: verbose_logging
# plugins:
  # - type: json_content_type_response
