server:
  port: 9000

logger:
  level: debug
  format: pretty

sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/

endpoints:
  - path: /graphql
    from: countries
      
  - path: /test
    from: countries
    plugins:
      - type: verbose_logging